### ISSUE TITLE
Small typo, should probably be "no-chaotics-repo" instead of "chaotics-repo"

### ISSUE THREAD

**Issue by hlestrat** [arconetpro/arcoplasma-iso#1]
Here is the line concerned :
https://github.com/arconetpro/arcoplasma-iso/blob/d4c6defd026d160f177c31b938fe997e4cfac52b/installation-scripts/30-build-the-iso-the-first-time.sh#L219

**Comment by arcolinuxz** [comment]
no it is correct 

we need the kernel from them
